global proc int sfa_zct()
{
    
    string $selection[] = `ls -sl`;
    
    for($obj in $selection)
    {
        
        float $m[] = `xform -q -m $obj`;
        setAttr -type "matrix" ($obj + ".offsetParentMatrix") $m[0] $m[1] $m[2] $m[3] $m[4] $m[5] $m[6] $m[7] $m[8] $m[9] $m[10] $m[11] $m[12] $m[13] $m[14] $m[15];
        xform -m 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 $obj;
        
    }
    
    return 0;
    
}